
server:
  port: 1020
  
spring:
  application:
    name: zuul-server

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1010/eureka
      
management: 
  endpoints: 
    web: 
      exposure: 
        include: 'routes'
